force-app/main/default/objects/Material_Items__c/Material_Items__c.object-meta.xml
<CustomObject>
    <description>Vertiba 5/22/14 - Detail object for Contacts to track Sunshine Act compliance report expenses as well as expenses for non-MDs from individual sales calls and group events. Data is used to populate quarterly Sunshine Act Compliance Report for contacts with prof. designation regulated by Sunshine Act.</description>
    <label>Material Item</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Material Items #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Material_Items__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Vertiba 5/22/14 - creates detail relationship to Contacts to track Sunshine Act compliance report expenses as well as expenses for non-MDs from individual sales calls and group events. Data is used to populate quarterly Sunshine Act Compliance Report for contacts with prof. designation regulated by Sunshine Act</description>
    <inlineHelpText>Contact which has received material items</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Material Items</relationshipLabel>
    <relationshipName>Material_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/activityTrackerApexController.cls
public with sharing class  activityTrackerApexController {
    
    @AuraEnabled 
    public static String saveActivity(Task task,List<Material_Items__c> materialItems){
    
     try{
        
        List<Contact> contacts = [Select AccountId From Contact Where Id = :task.WhoId limit 1];
        task.WhatId = contacts[0].AccountId;
        task.Priority = 'Normal';
         
         for(Material_Items__c materialItem : materialItems){
             materialItem.Contact__c = task.WhoId;
         }
        insert task;
        
        insert materialItems; 
        return 'SUCCESS';
    
     }catch(Exception e){            
         system.debug('ERROR' + e.getMessage());
         return 'ERROR';
     }
    
    }
    
    
}